[project]
name = "effective-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.1",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.8",
]
